version: '3.8'

services:
  service1:
    build:
      context: ./service_1
    container_name: service1
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      retries: 3
    networks:
      - app-network

  service2:
    build:
      context: ./service_2
    container_name: service2
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
